# Generated by Django 4.1.4 on 2022-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customguardian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGuardian',
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
