# Generated by Django 4.1.4 on 2022-12-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtor',
            old_name='admin_image',
            new_name='debtor_image',
        ),
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
