# Generated by Django 4.1.4 on 2022-12-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_admin_image_debtor_debtor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='debtor_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='document',
            field=models.FileField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='admin_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
