# Generated by Django 4.1.4 on 2022-12-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_debtor_debtor_image_alter_message_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schooladmin',
            name='CAC_no',
        ),
        migrations.RemoveField(
            model_name='schooladmin',
            name='date_of_est',
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='email',
            field=models.EmailField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='email',
            field=models.EmailField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(default='', max_length=120),
        ),
    ]
