# Generated by Django 4.1.4 on 2022-12-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_debtor_date_remove_schooladmin_cac_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='phone_no',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
